### ISSUE TITLE
registry 换成 zookeeper://127.0.0.1:2181 报错

### ISSUE THREAD

**Issue by QiuMing** [linux-china/spring-boot-dubbo#1]
大大你好，我尝试着把注册中心换成spring.dubbo.registry = zookeeper://127.0.0.1:2181
就报下面的错误，我确定我的zookeeper 是运行的，请问你知道是什么原因 嘛，还有请问使用redis 作为注册中心 有什么优势否
`Caused by: java.lang.NoClassDefFoundError: org/I0Itec/zkclient/IZkStateListener
    at com.alibaba.dubbo.remoting.zookeeper.zkclient.ZkclientZookeeperTransporter.connect(ZkclientZookeeperTransporter.java:10) ~[dubbo-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
    at com.alibaba.dubbo.remoting.zookeeper.ZookeeperTransporter$Adpative.connect(ZookeeperTransporter$Adpative.java) ~[dubbo-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
    at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistry.<init>(ZookeeperRegistry.java:69) ~[dubbo-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
    at com.alibaba.dubbo.registry.zookeeper.ZookeeperRegistryFactory.createRegistry(ZookeeperRegistryFactory.java:37) ~[dubbo-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
    at com.alibaba.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:94) ~[dubbo-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
    at org.mvnsearch.spring.boot.dubbo.DubboOperationEndpoint.init(DubboOperationEndpoint.java:32) ~[spring-boot-starter-dubbo-1.0.0-SNAPSHOT.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133) ~[spring-beans-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    ... 23 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.I0Itec.zkclient.IZkStateListener
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_73]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_73]
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_73]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_73]
    ... 36 common frames omitted
`

**Comment by QiuMing** [comment]
问题解决了，是我没有添加zookeeper 的依赖
添加下面的依赖就好了
`<dependency>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
            <version>3.4.6</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.101tec</groupId>
            <artifactId>zkclient</artifactId>
            <version>0.4</version>
        </dependency>`
