### ISSUE TITLE
spring.dubbo.registry写多个地址启动报错

### ISSUE THREAD

**Issue by phoenixzsun** [linux-china/spring-boot-dubbo#6]
Caused by: java.lang.NumberFormatException: For input string: "2181,x.x.x.x:2181"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_121]
	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_121]
	at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_121]
	at com.alibaba.dubbo.common.URL.valueOf(URL.java:219) ~[classes/:na]
	at org.mvnsearch.spring.boot.dubbo.DubboOperationEndpoint.init(DubboOperationEndpoint.java:30)

**Comment by xunux** [comment]
zookeeper集群注册中心正确配置应该是
`spring.dubbo.registry.address=zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183`
或者
`spring.dubbo.registry.protocol=zookeeper
spring.dubbo.registry.address=127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183`

**Comment by linux-china** [comment]
请参考 @xunux  的做法
